// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by rudwD0jrIdlm8_WaPRVGBizg09LY2PHHs9IkJec5CVQ_aXcvKmeyOmVyrR3LIgpE8Sk_FYiq3tuhnX2PsZCJieLw.Y9_qCaK_zMhKLYpO_HF6jg.h2EVs5Ok4JyiYSXsg8QB-OrryIkBR-8jWNoNGKxKPJcprXYcru927KYDHaoJC7CA7pSdXnzXXR5SlZt8Ax-bvvIvZNGkgeIi1YXCFAySDJ6CvIMUAqalxf4jyRJmqHbWd7Mw9Hs0lh5ZTU5twUHpB4U39pO_gSPPKkGJfLzAo3IFAD6iNr7mCr5Ej4gyAw1p8atVayaxsnGB6gRB4tiE-hqqgQsBmePrAiojfJGhB08GvvzIxVMO09IYMDGMgenPpX_K4CzdgzzXVKFDgjGT5vdraF7cRfuv16bZWjLrqq9ejrbWDA7NA7RfKRE1nBIGpzlzdMfAfSgjct9zcKkgBp1LlxNu0xDj01AuJlFYX6TUBUQQbGIEg2_vH0IJj-Bh7aHzHw9I9kkpBORXJ5-csOgI61uzfgpq08Ee8xXzuHFcDrG0bibSBc59lRBoQ_tRnning the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXeFm7AdomYSAwYDt9KzKvN2uCbcz8t-s',
    appId: '1:1059357074376:android:3cb64b52bd4810329c96fd',
    messagingSenderId: '1059357074376',
    projectId: 'free-flutter-course-app',
    storageBucket: 'free-flutter-course-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCR3tE893F4tF2GqTI0JZwyp5gH2Uvqycw',
    appId: '1:1059357074376:ios:71d49f2842e76bb29c96fd',
    messagingSenderId: '1059357074376',
    projectId: 'free-flutter-course-app',
    storageBucket: 'free-flutter-course-app.appspot.com',
    iosClientId: '1059357074376-li6689m2hajcsbq7ro68ofhj6c2gelrf.apps.googleusercontent.com',
    iosBundleId: 'com.example.courseApp',
  );
}
